### ISSUE TITLE
Object store missing

### ISSUE THREAD

**Issue by adderek** [piroor/webextensions-lib-tab-favicon-helper#3]
If the object store is missing - it must be created in the `.onupgradeneeded` event. Currently this runs only when `event.oldVersion < 1` but should run whenever any of the stores is missing from `db.objectStoreNames`. **At least so I think.**

Without it there are plenty of errors on the console in _expireOldEntries:
- NotFoundError (legacy `error.code === 8`, newer `error.name === "NotFoundError") is thrown when calling `db.transaction(["non-existing-store-object"])`
- Error is thrown up and logged
- This repeats frequently as error is still there and object store is not re-created

**Comment by piroor** [comment]
Thanks, I've updated codes to create object stores if they are missing.
